blank_issues_enabled: true
contact_links:
  - name: "â“ Q&A - GitHub Discussions"
    url: https://github.com/maplibre/maplibre-react-native/discussions/categories/q-a
    about: If you have a question about using MapLibre React Native
  - name: "ğŸ’¬ Chat with us on Slack"
    url: https://slack.openstreetmap.us/
    about: "Join `#maplibre-react-native` on the Open Street Map Slack"