name: iOS

on:
  workflow_call:
  # Review calls this Workflow

jobs:
  build-ios:
    name: Build
    runs-on: macos-26
    defaults:
      run:
        working-directory: ./examples/react-native-app
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache Cocoapods
        uses: actions/cache@v5
        id: cocoapods-cache
        with:
          path: ./examples/react-native-app/ios/Pods
          key: alpha-${{ runner.os }}-cocoapods-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
          restore-keys: |
            alpha-${{ runner.os }}-cocoapods-${{ hashFiles('yarn.lock') }}-
            alpha-${{ runner.os }}-cocoapods-

      - name: Install Cocoapods
        run: yarn ios:pod-install

      - name: Cache Build
        uses: actions/cache@v5
        id: ios-build-cache
        with:
          path: ./examples/react-native-app/ios/build
          key: alpha-${{ runner.os }}-ios-build-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}-${{ hashFiles('MapLibreReactNative.podspec') }}-${{ hashFiles('src/**') }}-${{ hashFiles('ios/**') }}-${{ hashFiles('examples/**') }}
          restore-keys: |
            alpha-${{ runner.os }}-ios-build-${{ hashFiles('yarn.lock') }}-
            alpha-${{ runner.os }}-ios-build-

      - name: Build
        if: steps.ios-build-cache.outputs.cache-hit != 'true'
        # Like `react-native build-ios --mode Release` but adapted for simulators
        run: xcodebuild -workspace ios/MapLibreReactNativeExample.xcworkspace -scheme MapLibreReactNativeExample -configuration Release -sdk iphonesimulator -derivedDataPath ios/build

      - name: Upload App
        uses: actions/upload-artifact@v6
        with:
          name: ios-app
          # `.app` is a directory, so we have to archive one level above
          path: |
            ./examples/react-native-app/ios/build/Build/Products/Release-iphonesimulator
            !./examples/react-native-app/ios/build/Build/Products/Release-iphonesimulator/**
            ./examples/react-native-app/ios/build/Build/Products/Release-iphonesimulator/MapLibreReactNativeExample.app

  test-ios:
    name: Test
    needs: [build-ios]
    runs-on: macos-26
    defaults:
      run:
        working-directory: ./examples/react-native-app
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      - name: Download App
        uses: actions/download-artifact@v7
        with:
          name: ios-app
          path: ./examples/react-native-app/ios

      - name: Run Tests
        run: |
          xcrun simctl boot "iPhone 17 Pro"
          xcrun simctl install booted ./ios/MapLibreReactNativeExample.app
          export MAESTRO_DRIVER_STARTUP_TIMEOUT=600000
          maestro test ./e2e/tests --format junit

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: iOS Report
          path: |
            ./examples/react-native-app/report.xml
            ~/.maestro/tests/**/*
