name: iOS

on:
  workflow_call:
  # Review calls this Workflow

jobs:
  build-ios:
    name: Build ${{ matrix.new-arch && 'new' || 'old'}} Arch
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./examples/react-native-app
    strategy:
      matrix:
        new-arch: [false, true]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache Cocoapods
        uses: actions/cache@v4
        id: cocoapods-cache
        with:
          path: ./examples/react-native-app/ios/Pods
          key: ${{ runner.os }}-cocoapods-${{ matrix.new-arch && 'new' || 'old' }}-arch-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-${{ matrix.new-arch && 'new' || 'old' }}-arch-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-cocoapods-${{ matrix.new-arch && 'new' || 'old' }}-arch-

      - name: Install Cocoapods
        run: RCT_NEW_ARCH_ENABLED=${{ matrix.new-arch && '1' || '0' }} yarn ios:pod-install

      - name: Cache Build
        uses: actions/cache@v4
        id: ios-build-cache
        with:
          path: ./examples/react-native-app/ios/build
          key: ${{ runner.os }}-ios-build-${{ matrix.new-arch && 'new' || 'old' }}-arch-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}-${{ hashFiles('ios/**') }}
          restore-keys: |
            ${{ runner.os }}-ios-build-${{ matrix.new-arch && 'new' || 'old' }}-arch-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-ios-build-${{ matrix.new-arch && 'new' || 'old' }}-arch-

      - name: Build
        if: steps.ios-build-cache.outputs.cache-hit != 'true'
        # Like `react-native build-ios --mode Release` but adapted for simulators
        run: xcodebuild -workspace ios/MapLibreReactNativeExample.xcworkspace -scheme MapLibreReactNativeExample -configuration Release -sdk iphonesimulator -derivedDataPath ios/build

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-${{ matrix.new-arch && 'new' || 'old' }}-arch
          # `.app` is a directory, so we have to archive one level above
          path: |
            ./examples/react-native-app/ios/build/Build/Products/Release-iphonesimulator
            !./examples/react-native-app/ios/build/Build/Products/Release-iphonesimulator/**
            ./examples/react-native-app/ios/build/Build/Products/Release-iphonesimulator/MapLibreReactNativeExample.app

  test-ios:
    name: Test ${{ matrix.new-arch && 'new' || 'old'}} Arch
    needs: [build-ios]
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./examples/react-native-app
    strategy:
      matrix:
        new-arch: [false, true]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      - name: Download App
        uses: actions/download-artifact@v4
        with:
          name: ios-app-${{ matrix.new-arch && 'new' || 'old' }}-arch
          path: ./examples/react-native-app/ios

      - name: Run Tests
        run: |
          xcrun simctl boot "iPhone 15 Pro"
          xcrun simctl install booted ./ios/MapLibreReactNativeExample.app
          export MAESTRO_DRIVER_STARTUP_TIMEOUT=240000
          maestro test ./e2e --format junit

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: iOS Report ${{ matrix.new-arch && 'new' || 'old' }} Arch
          path: |
            ./examples/react-native-app/report.xml
            ~/.maestro/tests/**/*
